import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import obsidianmd from 'eslint-plugin-obsidianmd';

export default [
  {
    ignores: ['node_modules/', 'main.js']
  },
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tsparser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: './tsconfig.json',
        tsconfigRootDir: '.',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      obsidianmd,
    },
    rules: {
      quotes: ['error', 'single'],
      semi: ['error', 'always'],
      'no-console': 0,
      'block-scoped-var': 'error',
      curly: ['error', 'multi-line'],
      eqeqeq: 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-multi-spaces': 'error',
      'no-return-await': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'wrap-iife': 'error',
      yoda: 'error',
      'no-shadow': 1,
      'no-undef-init': 'error',
      'no-label-var': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': ['error', 'never'],
      'comma-spacing': ['error', { before: false, after: true }],
      'comma-style': ['error', 'last'],
      'eol-last': ['error', 'always'],
      'func-call-spacing': ['error', 'never'],
      'implicit-arrow-linebreak': ['error', 'beside'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
      'keyword-spacing': ['error', { before: true, after: true }],
      'max-len': ['error', { code: 150, tabWidth: 4, comments: 120, ignoreUrls: true }],
      'multiline-ternary': ['error', 'never'],
      'no-array-constructor': 'error',
      'no-lonely-if': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': ['error', { max: 2 }],
      'no-new-object': 'error',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-newline': ['error', { multiline: true }],
      'object-curly-spacing': ['error', 'never'],
      'operator-assignment': ['error', 'always'],
      'padded-blocks': ['error', 'never'],
      'spaced-comment': ['error', 'always'],
      'arrow-body-style': ['error', 'as-needed'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-confusing-arrow': ['error', { allowParens: true }],
      'no-duplicate-imports': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': ['error', { object: true, array: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'quote-props': ['error', 'as-needed'],
      'semi-spacing': 'error',
      'semi-style': ['error', 'last'],
      'space-before-blocks': ['error', 'always'],
      'space-before-function-paren': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      '@typescript-eslint/require-await': ['error'],
      '@typescript-eslint/no-floating-promises': ['error', {}],
      '@typescript-eslint/explicit-member-accessibility': ['error', { accessibility: 'explicit' }]
    }
  }
];
